config/routes.rb
Rails.application.routes.draw do
   root 'pages#home'
   get 'about', to: 'pages#about'
   resources :articles
   get 'signup', to: 'users#new'
   resources :users, except: [:new]
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   delete 'logout', to: 'sessions#destroy'
   resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    scope :ordered, -> { order(created_at: :desc) }
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 6, maximum: 100}
    validates :description, presence: true, length: { minimum: 12, maximum: 300}    
end    

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end    

app/models/category.rb
class Category < ApplicationRecord
    scope :ordered, -> { order(created_at: :desc) }
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true,
        uniqueness: { case_sensitive: false }, 
        length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
end        

app/models/user.rb
class User < ApplicationRecord
    scope :ordered, -> { order(created_at: :desc) }
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates :username, presence: true, 
                         uniqueness: { case_sensitive: false },
                         length: {minimum: 3, maximum: 25}
    validates :email, presence: true, 
                      uniqueness: { case_sensitive: false },
                      length: {maximum: 105},
                      format: {with: /\A\S+@.+\.\S+\z/}
    has_secure_password                                   
end    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]            
    end 

    def logged_in?
        !!current_user
    end     

    def require_user
        if !logged_in?
           flash[:alert] = "You must be logged in."
           redirect_to login_path 
        end      
    end    

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show    
    end
    
    def index
        @articles = Article.ordered.paginate(page: params[:page], per_page: 3 )
    end
    
    def new
        @article = Article.new
    end

    def edit
        set_article
    end    
    
    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if  @article.save
            flash[:notice] = "Article was created successfully"
            redirect_to @article         
        else
            render 'new'
        end    
    end
    
    def update
        
        if  @article.update(article_params)
            flash[:notice] = "Article was updated successfully."
            redirect_to @article
        else    
            render 'edit'
        end
    end 
    
    def destroy
        
        @article.destroy
        redirect_to articles_path
    end
    
    private
    
    def set_article
        @article = Article.find(params[:id])
    end
    
    def article_params
        params.require(:article).permit(:title, :description, category_ids:[])    
    end
    
    def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "You can only edit your articles"
            redirect_to @article
        end    
    end    

end    

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]

   
    def new
        @category = Category.new
    end    

    def index 
        @categories = Category.ordered.paginate(page: params[:page], per_page: 5 )
    end
    
    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.ordered.paginate(page: params[:page], per_page: 3 )
    end    

    def create
        @category = Category.new(category_params)
        if  @category.save
            flash[:notice] = "Category was created successfully"
            redirect_to @category      
        else
            render 'new'
        end 
    end   

    def edit
        @category = Category.find(params[:id])
    end
    
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category name updated successfully"
            redirect_to @category
        else
            render 'edit'
        end         
    end    
    
    private

    def category_params
        params.require(:category).permit(:name)    
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins can do that"
            redirect_to categories_path
        end    
    end   

end    

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end
    def about
    end        
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new    
    end
    
    def create    
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged successfully."
            redirect_to user
        else  
            flash.now[:alert] = "Your email or password was incorrect."
            render 'new'
        end      
    end    
    
    def destroy
        session[:user_id] = nil 
        flash[:notice] = "You were logged out."
        redirect_to root_path
    end    

end     

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show        
        @articles = @user.articles.ordered.paginate(page: params[:page], per_page: 3 )   
    end   
    def index
        @users = User.ordered.paginate(page: params[:page], per_page: 3 )
    end   

    def new
        @user = User.new
    end
    
    def edit        
    end
    
    def update      
        if @user.update(user_params)
            flash[:notice] = "Your account was updated successfully."
            redirect_to @user   
        else
            render 'edit'
        end    
    end    
    
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Your account was creates successfully."
            redirect_to articles_path
        else
            render 'new'
        end        
    end
    
    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and articles successfull deleted."
        redirect_to root_path        
    end    
    
    
    
    
    private   
    
    def user_params
         params.require(:user).permit(:username, :email, :password)
    end       
    
    def set_user
        @user = User.find(params[:id])
    end    

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your account"
            redirect_to @user
        end    
    end    
end    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
   <% @articles.each do |article| %>
        <div class="row justify-content-md-center ">
            <div class="col-8 mt-4 ">
                <div class="card text-center shadow  mb-5 bg-white rounded">
                    <div class="card-header font-italic">
                        by <%= link_to article.user.username, user_path(article.user) %>
    
                    </div>
                    <div class="card-body">
                        <h5 class="card-title "><%= link_to article.title, article_path(article), class: "text-success" %></h5>
                        <p class="card-text"><%= truncate(article.description, length:100) %></p>
                        <%= link_to 'View', article_path(article), class: "btn btn-outline-success"%>  
                        <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                            <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info"%>
                            <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?"} , class: "btn btn-outline-danger"%>                            
                        <% end %>
                    </div>                                    
                     <% if article.categories.any? %>
                        <div class="card-footer text-muted">  
                            <%= render article.categories %>
                        </div>
                    <% end %>                    
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
                            edited <%= time_ago_in_words(article.updated_at) %> ago.
                        </small>
                    </div>
                </div>
            </div>    
        </div>            
    <% end%>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class="container bg-info shadow-lg p-3 mb-5 rounded mt-3">
    
    <%= form_with(model: @article, local: true) do |f|%>
      
        <div class="form_group row">
            
            <%= f.label :title, class: "col-2 col-form-label mt-3 text-light" %>
            <div class="col-10">
                <%= f.text_field :title, class: "form-control mt-3 mr-3 shadow-lg rounded", placeholder: "Title of article" %>
            </div>         
            
        
            <%= f.label :description, class: "col-2 col-form-label mt-3 text-light" %>
            <div class="col-10">
                <%= f.text_area :description, rows: 10, class: "form-control mt-3 shadow-lg rounded", placeholder: " Description of article" %>
            </div>      
            
            <%= f.label :category, class: "col-2 col-form-label mt-3 text-light" %>
            <div class="col-4 mt-4">
                <%= f.collection_select(:category_ids, Category.all, :id,  :name, 
                    {:prompt => "Select one or more (can be blank)"}, { multiple: true, size: 3, class: "custom-select shadow-lg rounded"}) %>
            </div>   
        </div>    

        <div class="card-body">
            <%= link_to "Back", articles_path(@articles),data: { confirm: "Your article will be not saved!"}, class: " btn btn-outline-danger btn-lg "%>
            <%= f.submit class:"btn btn-outline-light btn-lg right "%>
        </div>  
    <%end%>    
</div>

app/views/articles/edit.html.erb
    <h1 class="text-center mt-3">Edit article</h1>
    <%= render 'form'%>

app/views/articles/index.html.erb
<h1 class="text-center mt-3">List of articles</h1>
<div class="flickr_pagination mt-3">
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article' %>
<div class="flickr_pagination mb-3">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-3">Create new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-3"><%= @article.title%></h2>
<div class="container">    
     <div class="row justify-content-md-center">
        <div class="col-8 mt-4 ">
            <div class="card text-center shadow  mb-5 bg-white rounded">
                <div class="card-header font-italic">
                    by <%= @article.user.username %>
                    <%= link_to image_tag("/assets/miniWorkerAvatar.jpg"), user_path(@article.user) %> 
                </div>
                 <div class="card-body">
                    <div class="card-text text-left"><%= simple_format(@article.description)  %></div>                            
                        <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
                            <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info"%>
                            <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?"} , class: "btn btn-outline-danger"%>                            
                        <% end %>
                    </div>
                 <% if @article.categories.any? %>
                        <div class="card-footer text-muted">  
                            <%= render @article.categories %>
                        </div>
                <% end %>      
                <div class="card-footer text-muted">                  
                    <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
                        edited <%= time_ago_in_words(@article.updated_at) %> ago.
                    </small>
                </div>
            </div>
        </div>    
    </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<div class="container bg-info shadow-lg p-3 rounded mt-3" id='new-category-container'>    
    <%= form_with(model: @category, local: true) do |f|%>      
        <div class="form_group row">            
            <%= f.label :name, "Name" ,class: "col-2 col-form-label mt-3 text-light" %>
            <div class="col-9">
                <%= f.text_field :name, class: "form-control mt-3 mr-3 shadow-lg rounded", placeholder: "Enter a name" %>
            </div>          
        </div>    
        <div class="card-body">
            <%= link_to "Back", categories_path, data: { confirm: "Your category will be not created!"}, class: " btn btn-outline-danger btn-lg "%>
            <%= f.submit class:"btn btn-outline-light btn-lg right " %>
        </div>        
    <%end%>
</div>
    

app/views/categories/edit.html.erb
<h1 class="text-center mt-3">Edit category name</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-3">Categories</h1>
<div class="flickr_pagination mt-3">
    <%= will_paginate @categories, :container => false %>
</div>
<div class="container">
   <% @categories.each do |category| %>
        <div class="row justify-content-md-center ">
            <div class="col-4 mt-4 ">
                <div class="card text-center shadow  mb-5 bg-white rounded">
                    <div class="card-body">
                        <h5 class="card-title "><%= link_to category.name, category_path(category), class: "text-success" %></h5>                         
                    </div>
                    <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>                    
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(category.created_at) %> ago, edited <%= time_ago_in_words(category.updated_at) %> ago</small>
                    </div>
                </div>
            </div>    
        </div>            
    <% end%>
</div>
<div class="flickr_pagination mb-3">
    <%= will_paginate @categories, :container => false %>
</div>  

app/views/categories/new.html.erb
<h1 class="text-center mt-3">Create a new category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h2 class="text-center mt-3">Category: <%= @category.name %></h2>
<div class="text-center mt-3 ">
    <% if logged_in? && current_user.admin? %>        
        <%= link_to 'Edit', edit_category_path(@category), class: "btn btn-outline-info"%>               
    <% end %>
</div>

<h3 class="text-center mt-3">Articles</h3>
<div class="flickr_pagination mt-3">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mt-3">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
    <div class="container text-center">
        <small>Copyright &copy; Your Website</small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
    <% flash.each do |name, msg| %>
        <% if name == "notice" %>
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <%= msg %>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <% elsif name == "alert" %>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <%= msg %>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <% end %>    
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">                         
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% if logged_in? && current_user.admin? %>
                  <%= link_to "Create new category", new_category_path, class: "dropdown-item"%>
                <% end %>
                <%= link_to "View categories", categories_path, class: "dropdown-item"%>                
              </div>
            </li>            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Articles
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% if logged_in? %>
                  <%= link_to "Create new article", new_article_path, class: "dropdown-item"%>
                <% end %>
                <%= link_to "View articles", articles_path, class: "dropdown-item"%>                        
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>   
            <li class="nav-item">
              <%= link_to "Users", users_path, class: "nav-link"%>
            </li>          
            <% if logged_in? %>              
              <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.username%><%= "(Admin)" if current_user.admin? %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "View profile", user_path(current_user), class: "dropdown-item"%>
                <%= link_to "Edit profile", edit_user_path(current_user), class: "dropdown-item"%>                        
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
              </li>          
              <li class="nav-item">
                  <%= link_to "Log out", logout_path, class: "nav-link", method: :delete %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Log in", login_path, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "Sign up", signup_path, class: "nav-link"%>
              </li>
            <% end %>
            
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
      </div>
    </nav>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column ">  
    <%= render 'layouts/navigation' %>     
    <div id="page-content">
      <%= render 'layouts/messages' %>    
      <%= yield %>     
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
This is about page

app/views/pages/home.html.erb
<div class="container" id='home-container'>
    <div class="jumbotron  text-center font-weight-bold">
        <h1 class="display-4">Alpha Blog</h1>
        <p></p>
        <p class="lead font-weight-bold" >Hello everbody on my Blog. Feel free to sign up and add content.</p>
        <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg"  %>
    </div>
</div>
  

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="container">
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <h4 class="alert-heading">The following errors prevended <%= obj.class.name.downcase %> from being save</h4>
            <ul>
                <% obj.errors.full_messages.each do |msg|%>
                        <FONT COLOR="#ff0000"><li><%= msg%></li></FONT>
                <% end %>
            </ul>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
<% end%>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="container bg-info shadow-lg p-3 mb-5 rounded">
    
    <%= form_with(model: @user, local: true) do |f|%>
      
        <div class="form_group row">
            
            <%= f.label :username, class: "col-2 col-form-label mt-3 text-light" %>
            <div class="col-10">
                <%= f.text_field :username, class: "form-control mt-3 mr-3 shadow-lg rounded", placeholder: "Enter your username" %>
            </div>         
            
        
            <%= f.label :email, class: "col-2 col-form-label mt-3 text-light" %>
            <div class="col-10">
                <%= f.email_field :email, class: "form-control mt-3 shadow-lg rounded", placeholder: "Enter your email" %>
            </div>

            <%= f.label :password, class: "col-2 col-form-label mt-3 text-light" %>
            <div class="col-10">
                <%= f.password_field :password, class: "form-control mt-3 shadow-lg rounded", placeholder: "Enter your password" %>
            </div>        
        </div>    

        <div class="card-body">
            <%= link_to "Back", root_path, data: { confirm: "Your account will be not created!"}, class: " btn btn-outline-danger btn-lg "%>
            <%= f.submit(@user.new_record? ? "Sign up" : "Update" , class:"btn btn-outline-light btn-lg right " ) %>
        </div>                       
     
        
    <%end%>

    
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-3">Edit account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-3">List of users</h1>
<div class="flickr_pagination mt-3">
    <%= will_paginate @users, :container => false %>
</div>
<div class="container">
   <% @users.each do |user| %>
        <div class="row justify-content-md-center ">
            <div class="col-8 mt-4 ">
                <div class="card text-center shadow  mb-5 bg-white rounded">
                    <div class="card-header font-italic">
                         <%= link_to user.username, user %>     
                    </div>
                    <div class="card-body">
                        <div class= "img-responsive center">
                            <%= link_to image_tag("/assets/workerAvatar.jpg"), user %>
                        </div>
                        <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
                        <%= link_to 'View profile', user, class: "btn btn-outline-success"%>  
                        <% if logged_in? %>                        
                            <% if  user == current_user %>
                                <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-info"%>
                            <% end %>
                            <% if current_user.admin? %>
                                <%= link_to 'Delete', user_path(user), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
                            <% end %>
                        <% end %>
                    </div>
                     <div class="card-footer text-muted">
                        <small>
                            Joined <%= time_ago_in_words(user.created_at) %> ago.                            
                        </small>
                    </div>
                </div>
            </div>    
        </div>            
    <% end%>
</div>

<div class="flickr_pagination mt-3">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-3">Sign up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-3"><%= @user.username %>'s profile </h1>
<div>
    <%= image_tag ("/assets/workerAvatar.jpg"), class: "img-responsive center"%>
</div>
<div class="text-center mt-3 ">
    <% if logged_in? %>
        <% if @user == current_user %>
            <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-outline-info"%>        
        <% end %>
        <% if @user == current_user || current_user.admin? %>
            <%= link_to 'Delete', user_path(@user), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
        <% end %>
    <% end %>
</div>

<h3 class="text-center mt-3">Articles</h3>
<div class="flickr_pagination mt-3">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article'%>

<div class="flickr_pagination mt-3">
    <%= will_paginate @articles, :container => false %>
</div>